export const backoffice: {
    app: import("./BackofficeApplication").default;
    'components/AbstractList': typeof AbstractList;
    'components/BackofficeNav': typeof BackofficeNav;
    'components/HeaderPrimary': typeof HeaderPrimary;
    'components/HeaderSecondary': typeof HeaderSecondary;
    'components/PermanentDeleteButton': typeof PermanentDeleteButton;
    'components/SearchInput': typeof SearchInput;
    'components/SoftDeleteButton': typeof SoftDeleteButton;
    'components/SubmitButton': typeof SubmitButton;
    'components/UserList': typeof UserList;
    'components/UserSortDropdown': typeof UserSortDropdown;
    'pages/DashboardPage': typeof DashboardPage;
    'pages/UserIndexPage': typeof UserIndexPage;
    'pages/UserShowPage': typeof UserShowPage;
    'resolvers/UserListState': typeof ExtensionPageResolver;
    'states/UserListState': typeof UserListState;
};
import AbstractList from "./components/AbstractList";
import BackofficeNav from "./components/BackofficeNav";
import HeaderPrimary from "./components/HeaderPrimary";
import HeaderSecondary from "./components/HeaderSecondary";
import PermanentDeleteButton from "./components/PermanentDeleteButton";
import SearchInput from "./components/SearchInput";
import SoftDeleteButton from "./components/SoftDeleteButton";
import SubmitButton from "./components/SubmitButton";
import UserList from "./components/UserList";
import UserSortDropdown from "./components/UserSortDropdown";
import DashboardPage from "./pages/DashboardPage";
import UserIndexPage from "./pages/UserIndexPage";
import UserShowPage from "./pages/UserShowPage";
import ExtensionPageResolver from "./resolvers/ExtensionPageResolver";
import UserListState from "./states/UserListState";
